version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.1.2
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "network.host=_site_"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:5.1.2
    container_name: kibana
    links:
      - elasticsearch
    ports:
      - "5601:5601"
